apiVersion: vl
kind: Service
metadata:
  name: spark-driver—example
  namespace: default
spec:
clusterIP: None
- port: 29413
  protocol: TCP
  targetPort: 29413
selector:
  joo: spark-job
sessionAffinity: None
type: ClusterIP