apiVersion: extensions/vlbetal
kind: Deployment
metadata:
  name: spark-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      job: spark-job
template:
  metadata:
    labels:
      job: spark-job
  spec:
    containers:
    - args:
      — '/opt/spark/bin/spark-submit ../examples/src/main/python/pi.py 100000; tail -f /dev/null;'
      command :
      - /bin/sh
      - -c
      image: cnvrg/custom:spark-2.4.4
      imagePuUPolicy: Always
      name: main
      resources:
        requests:
          cpu: "1.5"
          memory: 1Gi
      volumeMounts:
      - mountPath: /opt/spark/conf
        name: spark-config
    imagePullSecrets:
    - name: regcred
    serviceAccount: spark
    serviceAccountName: spark
    volumes:
    - configMap: 
        name: spark-config
      name: spark-config