# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-app
  labels:
    app: spark-app # Add a label here to match the selector
spec:
  replicas: 1 # Update as needed
  selector:
    matchLabels:
      app: spark-app # Match the label in template.metadata.labels
  template:
    metadata:
      labels:
        app: spark-app # Match the label in selector.matchLabels
    spec:
      containers:
        - name: spark-app-container
          image: spark:latest
