apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-app
selector:
  matchLabels:
    app: spark-app
spec:
  template:
    spec:
      containers:
        - name: application-container
          image: spark:latest
